config/routes.rb
Rails.application.routes.draw do
  get 'terms/index'

  get 'faq/index'

  get 'news/index'

  resources :reports

  resources :orders

  get 'welcome/index'

  devise_for :users, controllers: {registrations: 'registrations'}

  root 'welcome#index'

end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
  has_one :report

  #validates :date, :firts_name, :last_name, :address, :email, :city, :state, :zip, :country, :dob, :cc, :exp_month, :exp_year, :routing, :product, :qty, :price, :shipping_type, :presence => true
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    #El usuario esta autenticado?
    if user_signed_in?
      # Si el usuario es el administrador le muestra todas las ordenes registradas
      if current_user.is_admin == true && current_user.is_admin =! nil
        @orders = Order.all
      else
        #si no solo muestro las ordenes que ha creado el usuario actua
        @orders = Order.where(user_id: current_user.id)
      end
    else
      #Si no esta autenticado lo redirecciona al inicio y muestra una alerta
      redirect_to "/", alert: "Login is required!"
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show

  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create

    @order = Order.new(order_params)
    #recibo el id del usuario actual
    @order.user = current_user
    #guardo la fecha del servidor
    @order.create_date = Date.today

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
      #Existe al menos alguien logeado?
      if user_signed_in?
        if current_user.is_admin == true && current_user.is_admin =! nil?
          @order = Order.find(params[:id])
        else
          #Si el post solicitado no corresponde al usuario, le niega el servicio
          unless @order.user_id == current_user.id
            redirect_to orders_url(@order), alert: "This order is unavariable for you!"
          else
            @order = Order.find(params[:id])
          end
        end
      else
        redirect_to "/", alert: "Login is required!"
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:create_date, :firts_name, :last_name, :address, :email, :city, :state, :zip, :country, :dob, :cc, :exp_year, :exp_month, :routing, :product, :qty, :price, :shipping_type, :cvv, :phone, :billing_address, :comments, :user_id)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def is_current_admin?
    if current_user.is_admin == true && current_user.is_admin =! nil
      return true
    else
      return false
    end
  end
end

app/views/orders/_form.html.erb
<%= form_for @order, :html => { :class => 'form-horizontal' } do |f| %>
    <% shipping_origin_hash = {'India' => '1', 'USA' => '2'} %>
  <div class="col-md-6">
  <div class="form-group">
    <label for="first_name" class="control-label col-md-2">First Name</label>
    <div class="col-md-10">
      <%= f.text_field :firts_name, :id => 'first_name', :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <label for="last_name" class="control-label col-md-2">Last Name</label>
    <div class="col-md-10">
      <%= f.text_field :last_name, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <label for="phone" class="control-label col-md-2">Phone</label>
    <div class="col-md-10">
      <%= f.text_field :phone, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <label for="email" class="control-label col-md-2">E-mail</label>
    <div class="col-md-10">
      <%= f.email_field :email, :class => 'form-control' %>
    </div>
  </div> 
   <div class="form-group">
    <label for="dob" class="control-label col-md-2">DOB</label>
    <div class="col-md-10">
      <%= f.date_select :dob, :order => [:month, :day, :year], start_year: 1928, end_year: 1996, :class => 'form-control' %>
    </div>
 </div> 
  <div class="form-group">
    <label for="address" class="control-label col-md-2">Address</label>
    <div class="col-md-10">
      <%= f.text_field :address, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <label for="city" class="control-label col-md-2">City</label>
    <div class="col-md-10">
      <%= f.text_field :city, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <label for="first_name" class="control-label col-md-2">State</label>
    <div class="col-md-10">
      <%= f.text_field :state, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <label for="zip" class="control-label col-md-2">Zip</label>
    <div class="col-md-10">
      <%= f.text_field :zip, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <label for="country" class="control-label col-md-2">Country</label>
    <div class="col-md-10">
      <%= f.text_field :country, :class => 'form-control' %>
    </div>
 </div>
 <div class="form-group">
    <label for="billing_address" class="control-label col-md-2">Billing Address</label>
    <div class="col-md-10">
      <%= f.text_field :billing_address, :class => 'form-control' %>
    </div>
 </div>

</div><!--END FIRST COLUMN-->
 <div class="col-md-6">
 <div class="form-group">
    <label for="cc" class="control-label col-md-2">Card Number</label>
    <div class="col-md-10">
      <%= f.number_field :cc, :class => 'form-control' %>
    </div>
 </div>
 <div class="form-group">
    <label for="cvv" class="control-label col-md-2">CVV</label>
    <div class="col-md-10">
        <%= f.text_field :cvv, :class => 'form-control' %>
    </div>
 </div>
  <div class="form-group">
    <label for="exp_month" class="control-label col-md-2">Exp. Date</label>
    <div class="col-md-10">
        <% months = (1..12).to_a.sort! %>
        <%= f.select :exp_month, months %> / 
        <% years = (2014..2030).to_a.sort! %>
        <%= f.select :exp_year, years %>
    </div>
  </div>

   <div class="form-group">
    <label for="price" class="control-label col-md-2">Price</label>
    <div class="col-md-10">
      <%= f.text_field :price, :id => 'price', :class => 'form-control' %></div>
  </div>
    <div class="form-group">
    <label for="product" class="control-label col-md-2">Product</label>
    <div class="col-md-10">
      <%= f.text_field :product, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <label for="qty" class="control-label col-md-2">Quantity</label>
    <div class="col-md-10">
      <%= f.number_field :qty, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <label for="shipping_type" class="control-label col-md-2">Shipping</label>
    <div class="col-md-10">
      <%= f.select(:shipping_type,shipping_origin_hash, { :class => 'select-block mbn' }) %>
    </div>
  </div>
  <div class="form-group">
    <label for="comments" class="control-label col-md-2">Comments</label>
    <div class="col-md-10">
      <%= f.text_field :comments, :class => 'form-control' %>
    </div>
  </div> 
  <% if is_current_admin? %>
  <div class="form-group">
    <label for="user_id" class="control-label col-md-2">Affiliate</label>
    <div class="col-md-10">
      <%= f.text_field :user_id, :class => 'form-control' %>
    </div>
  <% end %>
 </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-xs btn-info' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                orders_path, :class => 'btn btn-xs btn-danger' %>
  </div>
 </div><!--END SECOND COLUMN-->
<% end %>

app/views/orders/edit.html.erb
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
<%- model_class = Order -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>
</div>

app/views/orders/index.html.erb
<%- model_class = Order -%>

<div class="page-header">
  <h2><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h2>
</div>
<!--div class="container table-responsive"-->

  <table class="table table-striped table-condensed table-bordered table-hover table-hover table-checkable table-colvis datatable">
    <thead>
      <tr>
        <th>Order ID</th>
        <th>Customer</th>
        <th>Phone</th>
        <th>E-mail</th>
        <!--th>Address</th>
        <th>City</th>
        <th>State</th>
        <th>Zip</th-->
        <th>Country</th>
        <!--th>DOB</th>
        <th>Card Number</th>
        <th>CVV</th>
        <th>Exp. Date</th-->
        <th>Product</th>
        <th>Price</th>
        <th>Shipping</th>
        <% if is_current_admin? %>
            <th><%= model_class.human_attribute_name(:user_id) %></th>
        <% end %>
        <th>Date</th>
        <% if is_current_admin? %>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td>MRX-12<%= link_to order.id, order_path(order) %></td>
          <td><%= order.firts_name.titleize %> <%= order.last_name.titleize %></td>
          <td><%= order.phone %></td>
          <td><%= order.email %></td>
          <!--td><%= order.address.titleize %></td>          
          <td><%= order.city.titleize %></td>
          <td><%= order.state.upcase %></td>
          <td><%= order.zip %></td-->
          <td><%= order.country.upcase %></td>
          <!--td><%= order.dob %></td>
          <td><%= order.cc %></td>
          <td><%= order.cvv %></td>
          <td><%= order.exp_year %>/<%= order.exp_month %></td-->
          <td><%= order.product.titleize %> x <%= order.qty %></td>
          <td>$<%= order.price %></td>

          <% case order.shipping_type %>
            <% when 1 then %>
              <td><span class="label label-warning">India</span></td>
            <% when 2 then %>
              <td><span class="label label-primary">USA</span></td>              
          <% end %>
          <% if is_current_admin? %>
            <td><%= order.user.username %></td>
          <% end %>
          <td><%=l order.created_at %></td>
          <% if is_current_admin? %>
          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_order_path(order), :class => 'btn btn-xs btn-info' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        order_path(order),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure you want to delete this order?')) },
                        :class => 'btn btn-xs btn-danger' %>
          </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<!--/div-->

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_order_path,
            :class => 'btn btn-primary' %>

app/views/orders/new.html.erb
<%- model_class = Order -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/orders/show.html.erb
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
  <%- model_class = Order -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:create_date) %>:</strong></dt>
  <dd><%= @order.create_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:firts_name) %>:</strong></dt>
  <dd><%= @order.firts_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_name) %>:</strong></dt>
  <dd><%= @order.last_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @order.phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @order.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @order.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:city) %>:</strong></dt>
  <dd><%= @order.city %></dd>
  <dt><strong><%= model_class.human_attribute_name(:state) %>:</strong></dt>
  <dd><%= @order.state %></dd>
  <dt><strong><%= model_class.human_attribute_name(:zip) %>:</strong></dt>
  <dd><%= @order.zip %></dd>
  <dt><strong><%= model_class.human_attribute_name(:country) %>:</strong></dt>
  <dd><%= @order.country %></dd>
  <dt><strong><%= model_class.human_attribute_name(:billing_address) %>:</strong></dt>
  <dd><%= @order.billing_address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:dob) %>:</strong></dt>
  <dd><%= @order.dob %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cc) %>:</strong></dt>
  <dd><%= @order.cc %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cvv) %>:</strong></dt>
  <dd><%= @order.cvv %></dd>
  <dt><strong><%= model_class.human_attribute_name(:exp_year) %>:</strong></dt>
  <dd><%= @order.exp_year %></dd>
  <dt><strong><%= model_class.human_attribute_name(:exp_month) %>:</strong></dt>
  <dd><%= @order.exp_month %></dd>
  <dt><strong><%= model_class.human_attribute_name(:product) %>:</strong></dt>
  <dd><%= @order.product %></dd>
  <dt><strong><%= model_class.human_attribute_name(:qty) %>:</strong></dt>
  <dd><%= @order.qty %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @order.price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:shipping_type) %>:</strong></dt>
  <dd><%= @order.shipping_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:comments) %>:</strong></dt>
  <dd><%= @order.comments %></dd>
  <% if is_current_admin? %>
    <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
    <dd><%= @order.user_id %></dd>
  <% end %>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              orders_path, :class => 'btn'  %>
  <% if is_current_admin? %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_order_path(@order), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              order_path(@order),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
  <% end %>
</div>
</div>