config/routes.rb
Rails.application.routes.draw do
  get 'terms/index'

  get 'faq/index'

  get 'news/index'

  resources :reports

  resources :orders

  get 'welcome/index'

  devise_for :users, controllers: {registrations: 'registrations'}

  root 'welcome#index'

end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :order
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]
  # GET /reports
  # GET /reports.json
  def index
    if user_signed_in?
      # Si el usuario es el administrador le muestra todas las ordenes registradas
      if current_user.is_admin == true && current_user.is_admin =! nil
        @reports = Report.all
      else
        @reports = Report.where(id_user:  current_user.id)
      end
    else
      redirect_to "/", alert: "Login is required!"
    end
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    if current_user.is_admin == true && current_user.is_admin =! nil
      @report = Report.new
    else
      redirect_to "/", alert: "this option is only avariable for administrator users"
    end
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    if current_user.is_admin == true && current_user.is_admin =! nil
      @report = Report.new(report_params)
      @report.id_user = @report.order.user_id
      puts "---------------------------------"
      puts "#{@report.order.price}"
      puts "---------------------------------"
      @report.commission = 0.4 * (@report.order.price - 25)
      respond_to do |format|
        if @report.save
          format.html { redirect_to @report, notice: 'Report was successfully created.' }
          format.json { render :show, status: :created, location: @report }
        else
          format.html { render :new }
          format.json { render json: @report.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to "/", alert: "this option is only avariable for administrator users"
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:date_report, :status, :descriptor, :payment, :delivery, :settled, :commission, :account_dest,:order_id, :id_user, :tracking_number)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_for @report, :html => { :class => 'form-horizontal' } do |f| %>
    <% status_hash = {'New' => '1', 'Verified' => '2', 'Approved' => '3', 'Declined' => '4', 'Refund' => '5', 'Chargeback' => '6', 'Cancelled' => '7' } %>
    <% descriptor_hash = {'EASTERNWESTERNWELLNESS' => '4', 'PAYPAL' => '5', 'SOFTHUBWEB 855.260.8641' => '2'} %>
    <% payment_hash = {'Visa' => '1', 'Mastercard' => '2', 'American Express' => '3', 'Discover' => '4', 'Paypal' => '5', 'Money Oreder' => '6', 'Bitcoin' => '7'} %>
    <% delivery_hash = {'Pre-shipment' => '1', 'In Transit' => '2', 'Delivered' => '3'}%>
    <% settled_hash = {'No' => '1','Yes' => '2'} %>
    <div class="control-group">
    <%= f.label :status, :class => 'control-label' %>
    <div class="controls">
      <%= f.select(:status,status_hash, { :class => 'select-block mbn' }) %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :descriptor, :class => 'control-label' %>
    <div class="controls">
      <%= f.select(:descriptor,descriptor_hash, { :class => 'select-block mbn' }) %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :payment, :class => 'control-label' %>
    <div class="controls">
      <%= f.select(:payment,payment_hash, { :class => 'select-block mbn' }) %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :delivery, :class => 'control-label' %>
    <div class="controls">
      <%= f.select(:delivery,delivery_hash, { :class => 'select-block mbn' }) %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :settled, :class => 'control-label' %>
    <div class="controls">
      <%= f.select(:settled,settled_hash, { :class => 'select-block mbn' }) %>
    </div>
  </div>
  <div class="control-group">
      <%= f.label :tracking_number, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :tracking_number, :class => 'text_field' %>
      </div>
  </div>
  <div class="control-group">
      <%= f.label :order_id, :class => 'control-label' %>
      <div class="row">
          <div class="controls col-lg-1">
            <%= f.text_field :order_id, :class => 'form-control' %>
          </div>
       </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                reports_path, :class => 'btn' %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
	<%- model_class = Report -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>
</div>

app/views/reports/index.html.erb
<%- model_class = Report -%> 
<div class="page-header">
  <h3><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h3>
</div>
<table class="table table-striped table-condensed table-bordered table-hover">
  <thead>
    <tr>
      <!--th><%= model_class.human_attribute_name(:id) %></th-->
      <th><%= model_class.human_attribute_name(:order_id) %></th>
      <th>Customer</th>      
      <th>Price</th>
      <th><%= model_class.human_attribute_name(:status) %></th>      
      <th><%= model_class.human_attribute_name(:payment) %></th>
      <th><%= model_class.human_attribute_name(:descriptor) %></th>
      <th><%= model_class.human_attribute_name(:tracking_number) %></th>
      <th><%= model_class.human_attribute_name(:delivery) %></th>      
      <th><%= model_class.human_attribute_name(:commission) %></th>
      <th><%= model_class.human_attribute_name(:settled) %></th>     
      <% if is_current_admin? %>
      <th><%= model_class.human_attribute_name(:id_user) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>      
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <!--td><%= link_to report.id, report_path(report) %></td-->
        <td>MRX-12<%= report.order_id %></td>
        <td><%= report.order.firts_name.titleize %> <%= report.order.last_name.titleize %></td>        
        <td>$<%= report.order.price %></td>
        <td>
          <% case report.status %>
              <% when 1 then %>
                  <span class="label label-warning">New</span>
              <% when 2 then %>
                  <span class="label label-info">Verified</span>
              <% when 3 then %>
                  <span class="label label-success">Approved</span>
              <% when 4 then %>
                  <span class="label label-danger">Declined</span>
              <% when 5 then %>
                  <span class="label label-primary">Refund</span>
              <% when 6 then %>
                  <span class="label label-danger">Chargeback</span>
              <% when 7 then %>
                  <span class="label label-danger">Cancelled</span>
          <% end %>
        </td>
        <td>
          <% case report.payment %>
              <% when 1 then %>
                  <img src="/assets/images/icons/cc/visa.png" alt="Visa" />
              <% when 2 then %>
                  <!--span class="label label-default">Mastercard</span-->
                  <img src="/assets/images/mastercard.png" alt="Mastercard" />
              <% when 3 then %>
                  <span class="label label-default">American Express</span>
              <% when 4 then %>
                  <span class="label label-default">Discover</span>
              <% when 5 then %>
                  <span class="label label-default">Paypal</span>
              <% when 6 then %>
                  <span class="label label-default">Money Order</span>
              <% when 7 then %>
                  <span class="label label-success">Bitcoin</span>
          <% end %>
        </td>        
        <td>
          <% case report.descriptor %>
              <% when '1' then %>
                  <span class="label label-default">OCEAN8</span>
              <% when '2' then %>
                  <span class="label label-default">SOFTHUBWEB 855.260.8641</span>                  
              <% when '3' then %>
                  <span class="label label-default">SIGNALDRIVE SPECS</span>
              <% when '4' then %>
                  <span class="label label-default">EASTERNWESTERNWELLNESS</span>
              <% when '5' then %>
                  <span class="label label-default">PAYPAL</span>                                    
          <% end %>
        </td>
        <td><%= report.tracking_number %></td>
        <td>
          <% case report.delivery %>
              <% when 1 then %>
                  <span class="label label-danger">Pre-Shipment</span>
              <% when 2 then %>
                  <span class="label label-warning">In Transit</span>
              <% when 3 then %>
                  <span class="label label-success">Delivered</span>
          <% end %>
        </td>        
        <td>$<%= report.commission %></td>
        <td>
          <% case report.settled %>
              <% when 1 then %>
                  <span class="label label-danger">No</span>
              <% when 2 then %>
                  <span class="label label-success">Yes</span>
          <% end %>
        </td>        
        <% if is_current_admin? %>
        <td><%= report.id_user %>-<%= report.order.user.username %></td>        
        <td><%=l report.created_at %></td>        
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_report_path(report), :class => 'btn btn-xs btn-info' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      report_path(report),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<% if is_current_admin? %>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_report_path,
            :class => 'btn btn-primary' %>
<% end %>

app/views/reports/new.html.erb
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
	<%- model_class = Report -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>
</div>

app/views/reports/show.html.erb
<%- model_class = Report -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd>
    <% case @report.status %>
        <% when 1 then %>
            <span class="label label-default">New</span>
        <% when 2 then %>
            <span class="label label-primary">Verified</span>
        <% when 3 then %>
            <span class="label label-success">Approved</span>
        <% when 4 then %>
            <span class="label label-danger">Declined</span>
        <% when 5 then %>
            <span class="label label-info">Refund</span>
        <% when 6 then %>
            <span class="label label-default">Chargeback</span>
        <% when 7 then %>
            <span class="label label-danger">Cancelled</span>
    <% end %>
  </dd>
  <dt><strong><%= model_class.human_attribute_name(:descriptor) %>:</strong></dt>
  <dd>
    <% case @report.descriptor %>
              <% when '1' then %>
                  <span class="label label-default">OCEAN8</span>
              <% when '2' then %>
                  <span class="label label-default">SOFTHUBWEB 855.260.8641</span>                  
              <% when '3' then %>
                  <span class="label label-default">SIGNALDRIVE SPECS</span>
              <% when '4' then %>
                  <span class="label label-default">EASTERNWESTERNWELLNESS</span>
              <% when '5' then %>
                  <span class="label label-default">PAYPAL</span>   
    <% end %>
  </dd>
  <dt><strong><%= model_class.human_attribute_name(:payment) %>:</strong></dt>
  <dd>
    <% case @report.payment %>
        <% when 1 then %>
            <span class="label label-default">Visa</span>
        <% when 2 then %>
            <span class="label label-default">Mastercard</span>
        <% when 3 then %>
            <span class="label label-default">American Express</span>
        <% when 4 then %>
            <span class="label label-default">Discover</span>
        <% when 5 then %>
            <span class="label label-default">Paypal</span>
        <% when 6 then %>
            <span class="label label-default">Money Order</span>
        <% when 7 then %>
            <span class="label label-success">Bitcoin</span>
    <% end %>
  </dd>
  <dt><strong><%= model_class.human_attribute_name(:delivery) %>:</strong></dt>
  <dd>
    <% case @report.delivery %>
        <% when 1 then %>
            <span class="label label-warning">Pre-Shipment</span>
        <% when 2 then %>
            <span class="label label-info">In Transit</span>
        <% when 3 then %>
            <span class="label label-success">Delivered</span>
    <% end %>
  </dd>
  <dt><strong><%= model_class.human_attribute_name(:settled) %>:</strong></dt>
  <dd>
    <% case @report.settled %>
        <% when 1 then %>
            <span class="label label-info">No</span>
        <% when 2 then %>
            <span class="label label-info">Yes</span>
    <% end %>
  </dd>
  <dt><strong><%= model_class.human_attribute_name(:commission) %>:</strong></dt>
  <dd><%= @report.commission %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tracking_number) %>:</strong></dt>
  <dd><%= @report.tracking_number %></dd>
  <dt><strong><%= model_class.human_attribute_name(:order_id) %>:</strong></dt>
  <dd><%= @report.order_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:id_user) %>:</strong></dt>
  <dd><%= @report.id_user %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              reports_path, :class => 'btn'  %>
  <% if is_current_admin? %>
  <%= link_to t('.new', :default => t("helpers.links.new")),
            new_report_path,
            :class => 'btn btn-primary' %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_report_path(@report), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              report_path(@report),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
  <% end %>
</div>